---
#
# Author: Aniruddha Gokhale
# CS4287/5287 Principles of Cloud Computing
# Created: Fall 2024
#
# Purpose:
#   This playbook can be used if you would like to try doing
#   the actions from the master playbook step by step. Simply
#   copy the next play from the master to here and execute
#   just this play and make sure it is working. If everything
#   works correctly, you may then terminate your VMs once again
#   and just run the master playbook end to end
#

#####################################################
### Play 9: Download and Install Kafka
#####################################################

- name: "Play 9a - Download Kafka Locally"
  hosts: LocalMC # Run on the local machine
  remote_user: "{{ local_user }}" # Use the local user
  gather_facts: no
  become: false # No need for sudo privileges

  tasks:
    # Import the child playbook to download Kafka.
    - import_tasks: tasks/playbook_download_kafka.yaml

- name: "Play 9b - Install Kafka on Cloud VMs"
  hosts: CloudVMs # Run on all cloud VMs
  remote_user: "{{ cloud_user }}" # Use the cloud user
  become: true # Use sudo privileges
  gather_facts: no

  tasks:
    # Import the child playbook to install Kafka.
    - import_tasks: tasks/playbook_install_kafka.yaml
