---
- name: Install required APT packages for Docker and Kubernetes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
      - lsb-release
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
