FROM python:3.8-slim

RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*

RUN pip install torch torchvision flask kafka-python Pillow

COPY ml_server.py /app/ml_server.py
EXPOSE 5000

CMD ["python /app/ml_server.py"]
