---
apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
spec:
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: python:3.9 # Use a Python image or a custom image
          command: ["python", "/scripts/consumer.py"] # Command to run the script
          volumeMounts:
            - name: script-volume
              mountPath: /scripts # Mounting the ConfigMap at /scripts
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: consumer-script-config # Name of the ConfigMap containing the script
  backoffLimit: 4 # Optional retry limit

